NORMAL_VOCAB = {
    "Education": [
        {'text': '教育', 'pinyin': 'jiào yù'},
        {'text': '学校', 'pinyin': 'xué xiào'},
        {'text': '学习', 'pinyin': 'xué xí'},
        {'text': '教师', 'pinyin': 'jiào shī'},
        {'text': '课程', 'pinyin': 'kè chénɡ'},
        {'text': '考试', 'pinyin': 'kǎo shì'},
        {'text': '学生', 'pinyin': 'xué shēnɡ'},
        {'text': '知识', 'pinyin': 'zhī shí'},
        {'text': '课堂', 'pinyin': 'kè tánɡ'},
        {'text': '书籍', 'pinyin': 'shū jí'},
        {'text': '研究', 'pinyin': 'yán jiū'},
        {'text': '学位', 'pinyin': 'xué wèi'},
        {'text': '评估', 'pinyin': 'pínɡ ɡū'},
        {'text': '辩论', 'pinyin': 'biàn lùn'},
        {'text': '实习', 'pinyin': 'shí xí'},
        {'text': '课外活动', 'pinyin': 'kè wài huó dònɡ'},
        {'text': '论文', 'pinyin': 'lùn wén'},
        {'text': '讲座', 'pinyin': 'jiǎnɡ zuò'},
        {'text': '学习方法', 'pinyin': 'xué xí fānɡ fǎ'},
        {'text': '学习环境', 'pinyin': 'xué xí huán jìnɡ'}
    ],
    "Work": [
        {'text': '职业', 'pinyin': 'zhí yè'},
        {'text': '工作', 'pinyin': 'ɡōnɡ zuò'},
        {'text': '职位', 'pinyin': 'zhí wèi'},
        {'text': '劳动市场', 'pinyin': 'láo dònɡ shì chǎnɡ'},
        {'text': '面试', 'pinyin': 'miàn shì'},
        {'text': '简历', 'pinyin': 'jiǎn lì'},
        {'text': '职业发展', 'pinyin': 'zhí yè fā zhǎn'},
        {'text': '工作环境', 'pinyin': 'ɡōnɡ zuò huán jìnɡ'},
        {'text': '同事', 'pinyin': 'tónɡ shì'},
        {'text': '领导', 'pinyin': 'lǐnɡ dǎo'},
        {'text': '任务', 'pinyin': 'rèn wù'},
        {'text': '责任', 'pinyin': 'zé rèn'},
        {'text': '加班', 'pinyin': 'jiā bān'},
        {'text': '福利', 'pinyin': 'fú lì'},
        {'text': '目标', 'pinyin': 'mù biāo'},
        {'text': '职业选择', 'pinyin': 'zhí yè xuǎn zé'},
        {'text': '工作满意度', 'pinyin': 'ɡōnɡ zuò mǎn yì dù'},
        {'text': '竞争', 'pinyin': 'jìnɡ zhēnɡ'},
        {'text': '职场文化', 'pinyin': 'zhí chǎnɡ wén huà'}
    ],
    "Health": [
        {'text': '健康', 'pinyin': 'jiàn kānɡ'},
        {'text': '饮食', 'pinyin': 'yǐn shí'},
        {'text': '锻炼', 'pinyin': 'duàn liàn'},
        {'text': '心理健康', 'pinyin': 'xīn lǐ jiàn kānɡ'},
        {'text': '生活方式', 'pinyin': 'shēnɡ huó fānɡ shì'},
        {'text': '疾病', 'pinyin': 'jí bìnɡ'},
        {'text': '营养', 'pinyin': 'yínɡ yǎnɡ'},
        {'text': '运动', 'pinyin': 'yùn dònɡ'},
        {'text': '睡眠', 'pinyin': 'shuì mián'},
        {'text': '压力', 'pinyin': 'yā lì'},
        {'text': '健身', 'pinyin': 'jiàn shēn'},
        {'text': '医疗', 'pinyin': 'yī liáo'},
        {'text': '预防', 'pinyin': 'yù fánɡ'},
        {'text': '体重', 'pinyin': 'tǐ zhònɡ'},
        {'text': '习惯', 'pinyin': 'xí ɡuàn'},
        {'text': '养生', 'pinyin': 'yǎnɡ shēnɡ'},
        {'text': '诊所', 'pinyin': 'zhěn suǒ'},
        {'text': '体检', 'pinyin': 'tǐ jiǎn'},
        {'text': '健康饮食', 'pinyin': 'jiàn kānɡ yǐn shí'},
        {'text': '药物', 'pinyin': 'yào wù'}
    ]
    ,
    "Travel": [
        {'text': '旅行', 'pinyin': 'lǚ xínɡ'},
        {'text': '目的地', 'pinyin': 'mù dì dì'},
        {'text': '行程', 'pinyin': 'xínɡ chénɡ'},
        {'text': '背包旅行', 'pinyin': 'bēi bāo lǚ xínɡ'},
        {'text': '文化体验', 'pinyin': 'wén huà tǐ yàn'},
        {'text': '交通', 'pinyin': 'jiāo tōnɡ'},
        {'text': '酒店', 'pinyin': 'jiǔ diàn'},
        {'text': '观光', 'pinyin': 'ɡuān ɡuānɡ'},
        {'text': '旅游景点', 'pinyin': 'lǚ yóu jǐnɡ diǎn'},
        {'text': '预算', 'pinyin': 'yù suàn'},
        {'text': '旅行保险', 'pinyin': 'lǚ xínɡ bǎo xiǎn'},
        {'text': '纪念品', 'pinyin': 'jì niàn pǐn'},
        {'text': '自然风光', 'pinyin': 'zì rán fēnɡ ɡuānɡ'},
        {'text': '旅行计划', 'pinyin': 'lǚ xínɡ jì huà'},
        {'text': '语言', 'pinyin': 'yǔ yán'},
        {'text': '美食', 'pinyin': 'měi shí'},
        {'text': '休闲', 'pinyin': 'xiū xián'},
        {'text': '冒险', 'pinyin': 'mào xiǎn'},
        {'text': '旅行团', 'pinyin': 'lǚ xínɡ tuán'},
        {'text': '旅行日志', 'pinyin': 'lǚ xínɡ rì zhì'}
    ],
    "Culture": [
        {'text': '文化', 'pinyin': 'wén huà'},
        {'text': '传统', 'pinyin': 'chuán tǒnɡ'},
        {'text': '节日', 'pinyin': 'jié rì'},
        {'text': '习俗', 'pinyin': 'xí sú'},
        {'text': '艺术', 'pinyin': 'yì shù'},
        {'text': '音乐', 'pinyin': 'yīn yuè'},
        {'text': '舞蹈', 'pinyin': 'wǔ dǎo'},
        {'text': '文学', 'pinyin': 'wén xué'},
        {'text': '语言', 'pinyin': 'yǔ yán'},
        {'text': '民俗', 'pinyin': 'mín sú'},
        {'text': '价值观', 'pinyin': 'jià zhí ɡuān'},
        {'text': '社会', 'pinyin': 'shè huì'},
        {'text': '习惯', 'pinyin': 'xí ɡuàn'},
        {'text': '服饰', 'pinyin': 'fú shì'},
        {'text': '美食', 'pinyin': 'měi shí'},
        {'text': '宗教', 'pinyin': 'zōnɡ jiào'},
        {'text': '文化差异', 'pinyin': 'wén huà chā yì'}
    ],
    "Technology": [
        {'text': '科技', 'pinyin': 'kē jì'},
        {'text': '互联网', 'pinyin': 'hù lián wǎnɡ'},
        {'text': '社交媒体', 'pinyin': 'shè jiāo méi tǐ'},
        {'text': '创新', 'pinyin': 'chuànɡ xīn'},
        {'text': '自动化', 'pinyin': 'zì dònɡ huà'},
        {'text': '应用程序', 'pinyin': 'yìnɡ yònɡ chénɡ xù'},
        {'text': '数据', 'pinyin': 'shù jù'},
        {'text': '设备', 'pinyin': 'shè bèi'},
        {'text': '网络安全', 'pinyin': 'wǎnɡ luò ān quán'},
        {'text': '人工智能', 'pinyin': 'rén ɡōnɡ zhì nénɡ'},
        {'text': '虚拟现实', 'pinyin': 'xū nǐ xiàn shí'},
        {'text': '电子商务', 'pinyin': 'diàn zǐ shānɡ wù'},
        {'text': '信息', 'pinyin': 'xìn xī'},
        {'text': '机器人', 'pinyin': 'jī qì rén'},
        {'text': '远程工作', 'pinyin': 'yuǎn chénɡ ɡōnɡ zuò'},
        {'text': '数字化', 'pinyin': 'shù zì huà'},
        {'text': '电子邮件', 'pinyin': 'diàn zǐ yóu jiàn'},
        {'text': '媒体', 'pinyin': 'méi tǐ'},
        {'text': '计算机', 'pinyin': 'jì suàn jī'},
        {'text': '科学', 'pinyin': 'kē xué'}
    ],
    "Environment": [
        {'text': '环境', 'pinyin': 'huán jìnɡ'},
        {'text': '自然', 'pinyin': 'zì rán'},
        {'text': '保护', 'pinyin': 'bǎo hù'},
        {'text': '气候变化', 'pinyin': 'qì hòu biàn huà'},
        {'text': '可持续性', 'pinyin': 'kě chí xù xìnɡ'},
        {'text': '生态', 'pinyin': 'shēnɡ tài'},
        {'text': '生物多样性', 'pinyin': 'shēnɡ wù duō yànɡ xìnɡ'},
        {'text': '污染', 'pinyin': 'wū rǎn'},
        {'text': '资源', 'pinyin': 'zī yuán'},
        {'text': '生态系统', 'pinyin': 'shēnɡ tài xì tǒnɡ'},
        {'text': '森林', 'pinyin': 'sēn lín'},
        {'text': '水源', 'pinyin': 'shuǐ yuán'},
        {'text': '动物', 'pinyin': 'dònɡ wù'},
        {'text': '环保', 'pinyin': 'huán bǎo'},
        {'text': '绿色能源', 'pinyin': 'lǜ sè nénɡ yuán'},
        {'text': '土壤', 'pinyin': 'tǔ rǎnɡ'},
        {'text': '垃圾处理', 'pinyin': 'lā jī chú lǐ'},
        {'text': '自然灾害', 'pinyin': 'zì rán zāi hài'},
        {'text': '保护区', 'pinyin': 'bǎo hù qū'},
        {'text': '生态平衡', 'pinyin': 'shēnɡ tài pínɡ hénɡ'}
    ],
    "Food": [
        {'text': '水果', 'pinyin': 'shuǐ ɡuǒ'},
        {'text': '苹果', 'pinyin': 'pínɡ ɡuǒ'},
        {'text': '香蕉', 'pinyin': 'xiānɡ jiāo'},
        {'text': '葡萄', 'pinyin': 'pú táo'},
        {'text': '米饭', 'pinyin': 'mǐ fàn'},
        {'text': '面包', 'pinyin': 'miàn bāo'},
        {'text': '可乐', 'pinyin': 'kě lè'},
        {'text': '纯净水', 'pinyin': 'chún jìnɡ shuǐ'},
        {'text': '羊肉', 'pinyin': 'yánɡ ròu'},
        {'text': '鸡肉', 'pinyin': 'jī ròu'}
    ]
}

DIALOG_VOCAB = {
    "Health": [
        [
            {'text': 'A: 你平时如何保持健康？',
             'role': 'question',
             'pinyin': 'nǐ pínɡ shí rú hé bǎo chí jiàn kānɡ？'},
            {'text': 'B: 我每天都去健身房锻炼',
             'role': 'answer',
             'pinyin': 'wǒ měi tiān dōu qù jiàn shēn fánɡ duàn liàn'},
            {'text': 'A: 听起来不错！你觉得锻炼对你有什么好处？',
             'role': 'question',
             'pinyin': 'tīnɡ qǐ lái bú cuò！nǐ jué de duàn liàn duì nǐ yǒu shén me hǎo chù'},
            {'text': 'B: 我觉得锻炼让我精力充沛',
             'role': 'answer',
             'pinyin': 'wǒ jué de duàn liàn rànɡ wǒ jīnɡ lì chōnɡ pèi'},
            {'text': 'A: 你通常锻炼多长时间？',
             'role': 'question',
             'pinyin': 'nǐ tōnɡ chánɡ duàn liàn duō chánɡ shí jiān？'},
            {'text': 'B: 我一般锻炼一个小时',
             'role': 'answer',
             'pinyin': 'wǒ yì bān duàn liàn yí ɡè xiǎo shí'},
            {'text': 'A: 饮食方面你有什么特别注意的吗？',
             'role': 'question',
             'pinyin': 'yǐn shí fānɡ miàn nǐ yǒu shén me tè bié zhù yì de mɑ？'},
            {'text': 'B: 我尽量多吃蔬菜和水果，少吃快餐',
             'role': 'answer',
             'pinyin': 'wǒ jìn liànɡ duō chī shū cài hé shuǐ ɡuǒ，shǎo chī kuài cān'},
            {'text': 'A: 很好！你有尝试过什么健康食谱吗？',
             'role': 'question',
             'pinyin': 'hěn hǎo！nǐ yǒu chánɡ shì ɡuò shén me jiàn kānɡ shí pǔ mɑ'},
            {'text': 'B: 有，我最近在做燕麦粥，既健康又美味。',
             'role': 'answer',
             'pinyin': 'yǒu， wǒ zuì jìn zài zuò yàn mài zhōu， jì jiàn kānɡ yòu měi wèi'}
        ],
        [
            {'text': 'A: 你最近身体怎么样？',
             'role': 'question',
             'pinyin': 'Nǐ zuìjìn shēntǐ zěnme yàng?'},
            {'text': 'B: 我感觉还不错。', 'role': 'answer', 'pinyin': 'Wǒ gǎnjué hái bùcuò'},
            {'text': 'A: 你有锻炼吗？', 'role': 'question', 'pinyin': 'Nǐ yǒu duànliàn ma?'},
            {'text': 'B: 有，我每周去健身房三次。',
             'role': 'answer',
             'pinyin': 'Yǒu, wǒ měi zhōu qù jiànshēnfáng sāncì.'},
            {'text': 'A: 除了健身，你平时喜欢做什么运动？',
             'role': 'question',
             'pinyin': 'Chúle jiànshēn, nǐ píngshí xǐhuān zuò shénme yùndòng?'},
            {'text': 'B: 我喜欢跑步和游泳。',
             'role': 'answer',
             'pinyin': 'Wǒ xǐhuān pǎobù hé yóuyǒng.'},
            {'text': 'A: 我也喜欢游泳！', 'role': 'question', 'pinyin': 'Wǒ yě xǐhuān yóuyǒng!'},
            {'text': 'B: 那我们下次可以一起去。',
             'role': 'answer',
             'pinyin': 'Nà wǒmen xià cì kěyǐ yīqǐ qù.'}
        ]
    ],
    "Work": [
        [{'text': 'A: 你现在的工作是什么？',
          'role': 'question',
          'pinyin': 'nǐ xiàn zài de ɡōnɡ zuò shì shén me'},
         {'text': 'B: 我在一家广告公司做设计师。',
          'role': 'answer',
          'pinyin': 'wǒ zài yì jiā ɡuǎnɡ ɡào ɡōnɡ sī zuò shè jì shī'},
         {'text': 'A: 听起来很好！你觉得这个行业的挑战是什么？',
          'role': 'question',
          'pinyin': 'tīnɡ qǐ lái hěn hǎo！nǐ jué de zhè ɡe hánɡ yè de tiǎo zhàn shì shén me'},
         {'text': 'B: 我觉得最大的挑战是要不断创新。',
          'role': 'answer',
          'pinyin': 'wǒ jué de zuì dà de tiǎo zhàn shì yào bú duàn chuànɡ xīn'},
         {'text': 'A: 你通常如何获取灵感呢？',
          'role': 'question',
          'pinyin': 'nǐ tōnɡ chánɡ rú hé huò qǔ línɡ ɡǎn ne？'},
         {'text': 'B: 我会浏览一些设计网站，参加设计展览。',
          'role': 'answer',
          'pinyin': 'wǒ huì liú lǎn yì xiē shè jì wǎnɡ zhàn，cān jiā shè jì zhǎn lǎn'},
         {'text': 'A: 这很不错！你觉得团队合作重要吗？',
          'role': 'question',
          'pinyin': 'zhè hěn bú cuò！nǐ jué de tuán duì hé zuò zhònɡ yào mɑ？'},
         {'text': 'B: 非常重要，团队的意见能帮助我看到不同的视角。',
          'role': 'answer',
          'pinyin': 'fēi chánɡ zhònɡ yào，tuán duì de yì jiàn nénɡ bānɡ zhù wǒ kàn dào bù tónɡ de shì jiǎo'},
         {'text': 'A: 你对未来的职业发展有什么计划？',
          'role': 'question',
          'pinyin': 'nǐ duì wèi lái de zhí yè fā zhǎn yǒu shén me jì huà'},
         {'text': 'B: 我希望能成为创意总监，带领团队做更大的项目。',
          'role': 'answer',
          'pinyin': 'wǒ xī wànɡ nénɡ chénɡ wéi chuànɡ yì zǒnɡ jiān， dài lǐnɡ tuán duì zuò ɡènɡ dà de xiànɡ mù.'}],
        [{'text': 'A: 你现在在哪家公司工作？',
          'role': 'question',
          'pinyin': 'Nǐ xiànzài zài nǎ jiā gōngsī gōngzuò?'},
         {'text': 'B: 我在一家科技公司做工程师。',
          'role': 'answer',
          'pinyin': 'Wǒ zài yījiā kējì gōngsī zuò gōngchéngshī.'},
         {'text': 'A: 你觉得工作怎么样？',
          'role': 'question',
          'pinyin': 'Nǐ juédé gōngzuò zěnme yàng?'},
         {'text': 'B: 挺有挑战性的，但我很喜欢。',
          'role': 'answer',
          'pinyin': 'Tǐng yǒu tiǎozhàn xìng de, dàn wǒ hěn xǐhuān.'},
         {'text': 'A: 你每天的工作内容是什么？',
          'role': 'question',
          'pinyin': 'Nǐ měitiān de gōngzuò nèiróng shì shénme?'},
         {'text': 'B: 我主要负责软件开发和测试。',
          'role': 'answer',
          'pinyin': 'Wǒ zhǔyào fùzé ruǎnjiàn kāifā hé cèshì.'},
         {'text': 'A: 听起来很有趣！', 'role': 'question', 'pinyin': 'Tīng qǐlái hěn yǒuqù!'}]
    ],
    "Food": [
        [{'text': 'A: 你喜欢尝试新食物吗？',
          'role': 'question',
          'pinyin': 'nǐ xǐ huān chánɡ shì xīn shí wù mɑ？'},
         {'text': 'B: 非常喜欢！我最近尝试了泰国菜，真是太好吃了。',
          'role': 'answer',
          'pinyin': 'fēi chánɡ xǐ huān！wǒ zuì jìn chánɡ shì le tài ɡuó cài，zhēn shì tài hǎo chī le。'},
         {'text': 'A: 泰国菜有什么特别之处？',
          'role': 'question',
          'pinyin': 'tài ɡuó cài yǒu shén me tè bié zhī chù？'},
         {'text': 'B: 它的味道非常丰富，酸、甜、辣都有。',
          'role': 'answer',
          'pinyin': 'tā de wèi dào fēi chánɡ fēnɡ fù，suān， tián， là dōu yǒu'},
         {'text': 'A: 你最喜欢的泰国菜是什么？',
          'role': 'question',
          'pinyin': 'nǐ zuì xǐ huān de tài ɡuó cài shì shén me？'},
         {'text': 'B: 我最喜欢冬阴功汤。',
          'role': 'answer',
          'pinyin': 'wǒ zuì xǐ huān dōnɡ yīn ɡōnɡ tānɡ'},
         {'text': 'A: 听起来不错！你有没有尝试过自己做？',
          'role': 'question',
          'pinyin': 'tīnɡ qǐ lái bú cuò！nǐ yǒu méi yǒu chánɡ shì ɡuò zì jǐ zuò？'},
         {'text': 'B: 我尝试过，但做得没有餐厅的好。',
          'role': 'answer',
          'pinyin': 'wǒ chánɡ shì ɡuò，dàn zuò dé méi yǒu cān tīnɡ de hǎo'},
         {'text': 'A: 你还有其他喜欢的菜吗？',
          'role': 'question',
          'pinyin': 'nǐ hái yǒu qí tā xǐ huān de cài mɑ？'},
         {'text': 'B: 我还喜欢意大利菜，特别是披萨和意大利面。',
          'role': 'answer',
          'pinyin': 'wǒ hái xǐ huān yì dà lì cài，tè bié shì pī sà hé yì dà lì miàn'}],
        [{'text': 'A: 你最喜欢的食物是什么？',
          'role': 'question',
          'pinyin': 'Nǐ zuì xǐhuān de shíwù shì shénme?'},
         {'text': 'B: 我喜欢拉面和年糕。',
          'role': 'answer',
          'pinyin': 'Wǒ xǐhuān lāmiàn hé niángāo.'},
         {'text': 'A: 听起来很好吃！你会自己做吗？',
          'role': 'question',
          'pinyin': 'Tīng qǐlái hěn hào chī! Nǐ huì zìjǐ zuò ma?'},
         {'text': 'B: 会的，我偶尔会尝试做菜。',
          'role': 'answer',
          'pinyin': "Huì de, wǒ ǒu'ěr huì chángshì zuò cài."},
         {'text': 'A: 你最擅长做什么菜？',
          'role': 'question',
          'pinyin': 'Nǐ zuì shàncháng zuò shénme cài?'},
         {'text': 'B: 我擅长做蛋炒饭。',
          'role': 'answer',
          'pinyin': 'Wǒ shàncháng zuò dàn chǎofàn.'},
         {'text': 'A: 你喜欢去餐厅吃饭吗？',
          'role': 'question',
          'pinyin': 'Nǐ xǐhuān qù cāntīng chīfàn ma?'},
         {'text': 'B: 是的，特别是和朋友一起去。',
          'role': 'answer',
          'pinyin': 'Shì de, tèbié shì hé péngyǒu yīqǐ qù.'}]
    ],
    "Culture": [
        [{'text': 'A: 你对中国的文化有兴趣吗？',
          'role': 'question',
          'pinyin': 'nǐ duì zhōnɡ ɡuó de wén huà yǒu xìnɡ qù mɑ?'},
         {'text': 'B: 我对中国的传统文化很感兴趣，尤其是书法。',
          'role': 'answer',
          'pinyin': 'wǒ duì zhōnɡ ɡuó de chuán tǒnɡ wén huà hěn ɡǎn xìnɡ qù，yóu qí shì shū fǎ'},
         {'text': 'A: 书法确实很美！你会写吗？',
          'role': 'question',
          'pinyin': 'shū fǎ què shí hěn měi！nǐ huì xiě mɑ？'},
         {'text': 'B: 我正在学习书法，但还需要多加练习。',
          'role': 'answer',
          'pinyin': 'Wǒ zhèngzài xuéxí shūfǎ, dàn hái xūyào duōjiā liànxí.'},
         {'text': 'A: 你觉得书法有什么特别的意义吗？',
          'role': 'question',
          'pinyin': 'Nǐ juédé shūfǎ yǒu shé me tèbié de yìyì ma?'},
         {'text': 'B: 我觉得书法不仅是一种艺术，也是表达情感的方式。',
          'role': 'answer',
          'pinyin': 'Wǒ juédé shūfǎ bùjǐn shì yī zhǒng yìshù, yěshì biǎodá qínggǎn de fāngshì.'},
         {'text': 'A: 你有没有参加过书法班？',
          'role': 'question',
          'pinyin': 'Nǐ yǒu méiyǒu cānjiāguò shūfǎ bān?'},
         {'text': 'B: 有，我参加过一个短期课程，老师很有经验。',
          'role': 'answer',
          'pinyin': 'Yǒu, wǒ cānjiāguò yīgè duǎnqí kèchéng, lǎoshī hěn yǒu jīngyàn.'},
         {'text': 'A: 学习过程中有什么有趣的事情吗？',
          'role': 'question',
          'pinyin': 'Xuéxí guòchéng zhōng yǒu shé me yǒuqù de shìqíng ma？'},
         {'text': 'B: 有一次我写错了字，老师幽默地说我创造了新字。',
          'role': 'answer',
          'pinyin': 'Yǒu yīcì wǒ xiě cuòle zì, lǎoshī yōumò de shuō wǒ chuàngzàole xīn zì'}],
        [{'text': 'A: 你对中国文化了解多少？',
          'role': 'question',
          'pinyin': 'Nǐ duì zhōngguó wénhuà liǎojiě duōshǎo?'},
         {'text': 'B: 我知道一些，比如传统节日和习俗。',
          'role': 'answer',
          'pinyin': 'Wǒ zhīdào yīxiē, bǐrú chuántǒng jiérì hé xísú.'},
         {'text': 'A: 你最喜欢哪个节日？',
          'role': 'question',
          'pinyin': 'Nǐ zuì xǐhuān nǎge jiérì?'},
         {'text': 'B: 我喜欢春节，因为很热闹。',
          'role': 'answer',
          'pinyin': 'Wǒ xǐhuān chūnjié, yīnwèi hěn rènào.'},
         {'text': 'A: 你知道春节有哪些习俗吗？',
          'role': 'question',
          'pinyin': 'Nǐ zhīdào chūnjié yǒu nǎxiē xísú ma?'},
         {'text': 'B: 有放鞭炮、吃团圆饭和给红包。',
          'role': 'answer',
          'pinyin': 'Yǒu fàng biānpào, chī tuányuán fàn hé gěi hóngbāo.'},
         {'text': 'A: 你有参加过春节庆祝活动吗？',
          'role': 'question',
          'pinyin': 'Nǐ yǒu cānjiāguò chūnjié qìngzhù huódòng ma?'},
         {'text': 'B: 有，去年我和朋友一起庆祝。',
          'role': 'answer',
          'pinyin': 'Yǒu, qùnián wǒ hé péngyǒu yīqǐ qìngzhù.'}]
    ],
    "Travel": [
        [{'text': 'A: 你最想去哪个地方旅行？',
          'role': 'question',
          'pinyin': 'Nǐ zuì xiǎng qù nǎge dìfāng lǚxíng？'},
         {'text': 'B: 我想去北京，体验他们的文化和美食。',
          'role': 'answer',
          'pinyin': 'Wǒ xiǎng qù běijīng, tǐyàn tāmen de wénhuà hé měishí'},
         {'text': 'A: 北京有很多好玩的地方！你想去哪些地方？',
          'role': 'question',
          'pinyin': 'Běijīng yǒu hěnduō hǎowán dì dìfāng! Nǐ xiǎng qù nǎxiē dìfāng？'},
         {'text': 'B: 我想去故宫和长城。',
          'role': 'answer',
          'pinyin': 'Wǒ xiǎng qù gùgōng hé chángchéng'},
         {'text': 'A: 你对北京的美食有什么期待吗？',
          'role': 'question',
          'pinyin': 'Nǐ duì běijīng dì měishí yǒu shé me qídài ma?'},
         {'text': 'B: 我想尝试正宗的炸酱面，听说很好吃。',
          'role': 'answer',
          'pinyin': 'Wǒ xiǎng chángshì zhèngzōng de zhá jiàng miàn, tīng shuō hěn hào chī'},
         {'text': 'A: 你打算什么时候去旅行？',
          'role': 'question',
          'pinyin': 'Nǐ dǎsuàn shénme shíhòu qù lǚxíng?'},
         {'text': 'B: 我计划明年春天去。',
          'role': 'answer',
          'pinyin': 'Wǒ jìhuà míngnián chūntiān qù.'},
         {'text': 'A: 你会和谁一起去？',
          'role': 'question',
          'pinyin': 'Nǐ huì hé shéi yīqǐ qù？'},
         {'text': 'B: 我打算和我的朋友一起去。',
          'role': 'answer',
          'pinyin': 'Wǒ dǎsuàn hé wǒ de péngyǒu yīqǐ qù.'}],
        [{'text': 'A: 你喜欢旅行吗？', 'role': 'question', 'pinyin': 'Nǐ xǐhuān lǚxíng ma?'},
         {'text': 'B: 非常喜欢，每年我都会去不同的地方。',
          'role': 'answer',
          'pinyin': 'Fēicháng xǐhuān, měinián wǒ dūhuì qù bùtóng dì dìfāng.'},
         {'text': 'A: 你去过哪些国家？',
          'role': 'question',
          'pinyin': 'Nǐ qùguò nǎxiē guójiā?'},
         {'text': 'B: 我去过加拿大，德国和美国。',
          'role': 'answer',
          'pinyin': 'Wǒ qùguò jiānádà, déguó hé měiguó.'},
         {'text': 'A: 哪个地方给你留下的印象最深？',
          'role': 'question',
          'pinyin': 'Nǎge dìfāng gěi nǐ liú xià de yìnxiàng zuìshēn?'},
         {'text': 'B: 波士顿的文化和美食让我很惊艳.',
          'role': 'answer',
          'pinyin': 'Bōshìdùn de wénhuà hé měishí ràng wǒ hěn jīngyàn.'},
         {'text': 'A: 你下一个旅行计划去哪里？',
          'role': 'question',
          'pinyin': 'Nǐ xià yīgè lǚxíng jìhuà qù nǎlǐ?'},
         {'text': 'B: 我打算去法国，想看看埃菲尔铁塔。',
          'role': 'answer',
          'pinyin': "Wǒ dǎsuàn qù fàguó, xiǎng kàn kàn āifēi'ěr tiětǎ"},
         {'text': 'A: 听起来很棒！希望你玩得愉快！',
          'role': 'question',
          'pinyin': 'Tīng qǐlái hěn bàng! Xīwàng nǐ wán dé yúkuài!'}]
    ]
}
