# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\")\n\x07Request\x12\x10\n\x08waveform\x18\x01 \x01(\x0c\x12\x0c\n\x04text\x18\x02 \x01(\t\"0\n\x08Response\x12$\n\x10scored_character\x18\x01 \x03(\x0b\x32\n.Character\"o\n\tCharacter\x12\x17\n\x0freference_phone\x18\x01 \x03(\t\x12\x18\n\x10recognized_phone\x18\x02 \x03(\t\x12\x13\n\x0bscore_phone\x18\x03 \x03(\x02\x12\x0c\n\x04xmin\x18\x04 \x01(\t\x12\x0c\n\x04xmax\x18\x05 \x01(\t2+\n\x07Service\x12 \n\tRecognize\x12\x08.Request\x1a\t.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=17
  _globals['_REQUEST']._serialized_end=58
  _globals['_RESPONSE']._serialized_start=60
  _globals['_RESPONSE']._serialized_end=108
  _globals['_CHARACTER']._serialized_start=110
  _globals['_CHARACTER']._serialized_end=221
  _globals['_SERVICE']._serialized_start=223
  _globals['_SERVICE']._serialized_end=266
# @@protoc_insertion_point(module_scope)
